#!/usr/bin/env bash
# configure-upstash.sh — Interactive script that writes a .env.local file
# from your Upstash Kafka credentials.
#
# Run this after completing the steps in deploy/upstash/SETUP.md.
#
# Usage:
#   ./deploy/scripts/configure-upstash.sh
#   ./deploy/scripts/configure-upstash.sh --output /path/to/.env.local

set -euo pipefail

OUTPUT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="${OUTPUT:-$PROJECT_ROOT/.env.local}"

# ── Prompt helpers ────────────────────────────────────────────────────────────
ask() {
  local prompt="$1" varname="$2" default="${3:-}"
  if [[ -n "$default" ]]; then
    read -r -p "  $prompt [$default]: " val
    eval "$varname=\"${val:-$default}\""
  else
    while true; do
      read -r -p "  $prompt: " val
      [[ -n "$val" ]] && break
      echo "    (required)"
    done
    eval "$varname=\"$val\""
  fi
}

ask_secret() {
  local prompt="$1" varname="$2"
  while true; do
    read -r -s -p "  $prompt: " val
    echo ""
    [[ -n "$val" ]] && break
    echo "    (required)"
  done
  eval "$varname=\"$val\""
}

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  Agent Mesh SRE — Upstash Kafka configuration                         │"
echo "│  (see deploy/upstash/SETUP.md for the step-by-step web UI guide)      │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
echo ""
echo "Values are on the cluster Overview page at https://console.upstash.com"
echo ""

# ── Collect values ────────────────────────────────────────────────────────────
ask "Bootstrap endpoint (e.g. knowing-condor-12345-us1-kafka.upstash.io:9092)" BOOTSTRAP
ask "Username" USERNAME
ask_secret "Password" PASSWORD

# ── Detect existing .env.local ────────────────────────────────────────────────
if [[ -f "$OUTPUT" ]]; then
  echo ""
  echo "⚠  $OUTPUT already exists."
  read -r -p "  Overwrite it? [y/N]: " confirm
  case "$confirm" in
    [yY]|[yY][eE][sS]) echo "  Overwriting." ;;
    *) echo "  Aborted. Use --output to write to a different path."; exit 0 ;;
  esac
fi

# ── Write .env.local ──────────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
# ── Generated by deploy/scripts/configure-upstash.sh on $(date -Iseconds) ──
# Upstash Kafka — free serverless Kafka cluster.
# See deploy/upstash/SETUP.md for setup instructions.

KAFKA_MODE=real
KAFKA_NAMESPACE=agent-mesh-sre
KAFKA_CLUSTER=agent-mesh-kafka

# Upstash Kafka bootstrap server
KAFKA_BOOTSTRAP=$BOOTSTRAP

# SASL/SCRAM-SHA-256 credentials (Upstash default)
KAFKA_USERNAME=$USERNAME
KAFKA_PASSWORD=$PASSWORD
KAFKA_SASL_MECHANISM=scram-sha-256

# No KAFKA_CA_CERT_BASE64 needed — Upstash uses public CAs

# ── SMTP (optional — for email notifications) ─────────────────────────────────
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-gmail@gmail.com
# SMTP_PASS=your-16-char-app-password
# NOTIFICATION_EMAIL=surajcs@gmail.com
EOF

echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  ✓ Written to: $OUTPUT"
echo "│                                                                        │"
echo "│  Start the app:                                                        │"
echo "│    npm run dev                                                         │"
echo "│    open http://localhost:3000                                          │"
echo "│                                                                        │"
echo "│  For Vercel — add these 5 vars in your project settings:              │"
echo "│    KAFKA_MODE, KAFKA_BOOTSTRAP, KAFKA_USERNAME,                        │"
echo "│    KAFKA_PASSWORD, KAFKA_SASL_MECHANISM                                │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
