#!/usr/bin/env bash
# configure-redpanda.sh — Interactive script that writes a .env.local file
# from your RedPanda Cloud Serverless credentials.
#
# Run this after completing the steps in deploy/redpanda/SETUP.md.
#
# Usage:
#   ./deploy/scripts/configure-redpanda.sh
#   ./deploy/scripts/configure-redpanda.sh --output /path/to/.env.local

set -euo pipefail

OUTPUT="${1:-}"
# Support --output flag
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Default: write to .env.local in the project root (one level up from scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="${OUTPUT:-$PROJECT_ROOT/.env.local}"

# ── Prompt helpers ────────────────────────────────────────────────────────────
ask() {
  local prompt="$1" varname="$2" default="${3:-}"
  if [[ -n "$default" ]]; then
    read -r -p "  $prompt [$default]: " val
    eval "$varname=\"${val:-$default}\""
  else
    while true; do
      read -r -p "  $prompt: " val
      [[ -n "$val" ]] && break
      echo "    (required — cannot be empty)"
    done
    eval "$varname=\"$val\""
  fi
}

ask_secret() {
  local prompt="$1" varname="$2"
  while true; do
    read -r -s -p "  $prompt: " val
    echo ""
    [[ -n "$val" ]] && break
    echo "    (required — cannot be empty)"
  done
  eval "$varname=\"$val\""
}

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  Agent Mesh SRE — RedPanda Cloud configuration                        │"
echo "│  (see deploy/redpanda/SETUP.md for the step-by-step web UI guide)     │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
echo ""
echo "Paste the values from your RedPanda Cloud cluster dashboard."
echo ""

# ── Collect values ────────────────────────────────────────────────────────────
ask "Bootstrap server (e.g. seed-xxxxx.cloud.redpanda.com:9092)" BOOTSTRAP
ask "SASL username" USERNAME "agent-mesh-controller"
ask_secret "SASL password" PASSWORD

# ── Detect existing .env.local ────────────────────────────────────────────────
if [[ -f "$OUTPUT" ]]; then
  echo ""
  echo "⚠  $OUTPUT already exists."
  read -r -p "  Overwrite it? [y/N]: " confirm
  case "$confirm" in
    [yY]|[yY][eE][sS]) echo "  Overwriting." ;;
    *) echo "  Aborted. Run with --output /path/to/other.env to write elsewhere."; exit 0 ;;
  esac
fi

# ── Write .env.local ──────────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
# ── Generated by deploy/scripts/configure-redpanda.sh on $(date -Iseconds) ──
# RedPanda Cloud Serverless — free Kafka cluster.
# See deploy/redpanda/SETUP.md for how to get these values.

KAFKA_MODE=real
KAFKA_NAMESPACE=agent-mesh-sre
KAFKA_CLUSTER=agent-mesh-kafka

# RedPanda bootstrap server
KAFKA_BOOTSTRAP=$BOOTSTRAP

# SASL/SCRAM-SHA-256 credentials (RedPanda default)
KAFKA_USERNAME=$USERNAME
KAFKA_PASSWORD=$PASSWORD
KAFKA_SASL_MECHANISM=scram-sha-256

# No KAFKA_CA_CERT_BASE64 needed — RedPanda uses Let's Encrypt (public CA)

# ── SMTP (optional — for email notifications) ─────────────────────────────────
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-gmail@gmail.com
# SMTP_PASS=your-16-char-app-password
# NOTIFICATION_EMAIL=surajcs@gmail.com
EOF

echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  ✓ Written to: $OUTPUT"
echo "│                                                                        │"
echo "│  Next steps:                                                           │"
echo "│    npm run dev                                                         │"
echo "│    open http://localhost:3000                                          │"
echo "│                                                                        │"
echo "│  For Vercel — add these 5 vars in your project settings:              │"
echo "│    KAFKA_MODE, KAFKA_BOOTSTRAP, KAFKA_USERNAME,                        │"
echo "│    KAFKA_PASSWORD, KAFKA_SASL_MECHANISM                                │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
