#!/usr/bin/env bash
# configure-aiven.sh — Interactive script that writes a .env.local file
# from your Aiven for Apache Kafka credentials.
#
# Run this after completing deploy/aiven/SETUP.md.
# You will need:
#   - Bootstrap URI  (Overview → Connection information → Service URI)
#   - Username       (Users tab → avnadmin)
#   - Password       (Users tab → avnadmin → show password)
#   - ca.pem file    (Overview → Connection information → Download CA cert)
#
# Usage:
#   ./deploy/scripts/configure-aiven.sh
#   ./deploy/scripts/configure-aiven.sh --output /path/to/.env.local

set -euo pipefail

OUTPUT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="${OUTPUT:-$PROJECT_ROOT/.env.local}"

# ── Prompt helpers ────────────────────────────────────────────────────────────
ask() {
  local prompt="$1" varname="$2" default="${3:-}"
  if [[ -n "$default" ]]; then
    read -r -p "  $prompt [$default]: " val
    eval "$varname=\"${val:-$default}\""
  else
    while true; do
      read -r -p "  $prompt: " val
      [[ -n "$val" ]] && break
      echo "    (required)"
    done
    eval "$varname=\"$val\""
  fi
}

ask_secret() {
  local prompt="$1" varname="$2"
  while true; do
    read -r -s -p "  $prompt: " val
    echo ""
    [[ -n "$val" ]] && break
    echo "    (required)"
  done
  eval "$varname=\"$val\""
}

ask_file() {
  local prompt="$1" varname="$2"
  while true; do
    read -r -p "  $prompt: " val
    # Expand ~ to $HOME
    val="${val/#\~/$HOME}"
    if [[ -f "$val" ]]; then
      eval "$varname=\"$val\""
      break
    fi
    echo "    File not found: $val — try again"
  done
}

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  Agent Mesh SRE — Aiven for Apache Kafka configuration                │"
echo "│  (see deploy/aiven/SETUP.md for the step-by-step web UI guide)        │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
echo ""
echo "Values are on the service Overview page at https://console.aiven.io"
echo ""

# ── Collect values ────────────────────────────────────────────────────────────
ask "Bootstrap URI (e.g. kafka-agent-mesh-yourproject.aivencloud.com:12691)" BOOTSTRAP
ask "Username" USERNAME "avnadmin"
ask_secret "Password" PASSWORD
ask_file "Path to downloaded ca.pem file (e.g. ~/Downloads/ca.pem)" CA_PEM_PATH

# ── Encode the CA cert ────────────────────────────────────────────────────────
echo ""
echo "  Encoding CA cert…"
CA_B64=$(base64 -i "$CA_PEM_PATH" 2>/dev/null || base64 < "$CA_PEM_PATH")
# Strip newlines from base64 output (macOS base64 wraps at 76 chars)
CA_B64=$(echo "$CA_B64" | tr -d '\n')
echo "  CA cert encoded (${#CA_B64} chars)"

# ── Merge into existing .env.local (preserve non-Kafka vars) ─────────────────
KAFKA_KEYS=(KAFKA_MODE KAFKA_NAMESPACE KAFKA_CLUSTER KAFKA_BOOTSTRAP KAFKA_USERNAME KAFKA_PASSWORD KAFKA_SASL_MECHANISM KAFKA_CA_CERT_BASE64)

if [[ -f "$OUTPUT" ]]; then
  echo ""
  echo "  Merging Kafka vars into existing $OUTPUT"
  echo "  (all other vars like NEXTAUTH_SECRET, GOOGLE_* etc. are preserved)"
  # Remove existing KAFKA_* lines then re-append
  TMPFILE=$(mktemp)
  grep -v '^KAFKA_' "$OUTPUT" > "$TMPFILE" || true
  mv "$TMPFILE" "$OUTPUT"
else
  echo "  Creating new $OUTPUT"
fi

# ── Write Kafka vars (append) ─────────────────────────────────────────────────
cat >> "$OUTPUT" <<EOF
# ── Generated by deploy/scripts/configure-aiven.sh on $(date -Iseconds) ──
# Aiven for Apache Kafka — \$300 free trial cluster.
# See deploy/aiven/SETUP.md for setup instructions.

KAFKA_MODE=real
KAFKA_NAMESPACE=agent-mesh-sre
KAFKA_CLUSTER=agent-mesh-kafka

# Aiven bootstrap server (host:port from service Overview)
KAFKA_BOOTSTRAP=$BOOTSTRAP

# SASL/SCRAM-SHA-256 credentials
KAFKA_USERNAME=$USERNAME
KAFKA_PASSWORD=$PASSWORD
KAFKA_SASL_MECHANISM=scram-sha-256

# Base64-encoded cluster CA cert (required for Aiven TLS)
KAFKA_CA_CERT_BASE64=$CA_B64

# ── SMTP (optional — for email notifications) ─────────────────────────────────
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-gmail@gmail.com
# SMTP_PASS=your-16-char-app-password
# NOTIFICATION_EMAIL=surajcs@gmail.com
EOF

echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  ✓ Written to: $OUTPUT"
echo "│                                                                        │"
echo "│  Start the app:                                                        │"
echo "│    npm run dev                                                         │"
echo "│    open http://localhost:3000                                          │"
echo "│                                                                        │"
echo "│  For Vercel — add these 6 vars in your project settings:              │"
echo "│    KAFKA_MODE, KAFKA_BOOTSTRAP, KAFKA_USERNAME, KAFKA_PASSWORD,        │"
echo "│    KAFKA_SASL_MECHANISM, KAFKA_CA_CERT_BASE64                          │"
echo "│                                                                        │"
echo "│  Copy KAFKA_CA_CERT_BASE64 from the .env.local file just written.      │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
