#!/usr/bin/env bash
# get-credentials-gke.sh — Extract the bootstrap server address, cluster CA
# cert, and SCRAM password for the agent-mesh-controller user, formatted as
# a .env.local file that the Next.js app reads at startup.
#
# GKE variant: reads the LoadBalancer IP from the Strimzi status, not a Route.
# The LoadBalancer can take 2-3 minutes to get an IP after the Kafka cluster
# becomes Ready — this script polls until it appears.
#
# Usage:
#   ./deploy/scripts/get-credentials-gke.sh > .env.local
#   ./deploy/scripts/get-credentials-gke.sh   (prints to stdout — redirect manually)

set -euo pipefail

NS="${NAMESPACE:-agent-mesh-sre}"
CLUSTER="${KAFKA_CLUSTER:-agent-mesh-kafka}"
USER="${KAFKA_USER:-agent-mesh-controller}"
MAX_WAIT=60   # max polling attempts (10s each = 10 min)

command -v kubectl >/dev/null || { echo "kubectl not found on PATH" >&2; exit 1; }

# ── Wait for external bootstrap address ──────────────────────────────────────
echo "▶ Waiting for external bootstrap address (LoadBalancer IP)…" >&2
bootstrap=""
for i in $(seq 1 $MAX_WAIT); do
  bootstrap=$(kubectl get kafka "$CLUSTER" -n "$NS" \
    -o jsonpath='{.status.listeners[?(@.name=="external")].bootstrapServers}' \
    2>/dev/null || true)
  # Reject empty or "pending" values
  if [[ -n "$bootstrap" && "$bootstrap" != *"pending"* && "$bootstrap" != *"<"* ]]; then
    echo "  Bootstrap: $bootstrap" >&2
    break
  fi
  echo "  Attempt $i/$MAX_WAIT — waiting 10s for LoadBalancer IP…" >&2
  sleep 10
  bootstrap=""
done

if [[ -z "$bootstrap" ]]; then
  echo "" >&2
  echo "✗ Timed out waiting for external bootstrap address." >&2
  echo "  Check cluster status: kubectl get kafka $CLUSTER -n $NS" >&2
  echo "  Check LB service:     kubectl get svc -n $NS | grep external" >&2
  exit 1
fi

# ── Extract CA cert ───────────────────────────────────────────────────────────
echo "▶ Extracting cluster CA cert…" >&2
ca_raw=$(kubectl get secret "${CLUSTER}-cluster-ca-cert" -n "$NS" \
  -o jsonpath='{.data.ca\.crt}' 2>/dev/null) || {
  echo "✗ Could not read ${CLUSTER}-cluster-ca-cert secret" >&2; exit 1
}
ca_pem=$(echo "$ca_raw" | base64 -d)
ca_b64=$(echo -n "$ca_pem" | base64 -w0 2>/dev/null || echo -n "$ca_pem" | base64)

# ── Extract SCRAM password ────────────────────────────────────────────────────
echo "▶ Extracting SCRAM password for $USER…" >&2
password=$(kubectl get secret "$USER" -n "$NS" \
  -o jsonpath='{.data.password}' 2>/dev/null | base64 -d) || {
  echo "✗ Could not read secret $USER in $NS" >&2; exit 1
}

# ── Emit .env.local ───────────────────────────────────────────────────────────
cat <<EOF
# ── Generated by deploy/scripts/get-credentials-gke.sh on $(date -Iseconds) ──
# Connects to the Strimzi Kafka cluster on GKE via the external LoadBalancer.
# Place this file at agent-mesh-sre/.env.local — Next.js picks it up on startup.
#
# To apply these same vars to Vercel:
#   Vercel Dashboard → Your project → Settings → Environment Variables
#   Add each key/value below (all environments: Production, Preview, Development).

KAFKA_MODE=real
KAFKA_NAMESPACE=$NS
KAFKA_CLUSTER=$CLUSTER

# External bootstrap (LoadBalancer IP:port assigned by GKE)
KAFKA_BOOTSTRAP=$bootstrap

# SCRAM-SHA-512 credentials for the agent-mesh-controller KafkaUser
KAFKA_USERNAME=$USER
KAFKA_PASSWORD=$password

# Base64-encoded cluster CA cert (for TLS verification)
KAFKA_CA_CERT_BASE64=$ca_b64
EOF

echo "" >&2
echo "✓ .env.local content written to stdout." >&2
echo "  Redirect with:  ./deploy/scripts/get-credentials-gke.sh > .env.local" >&2
