#!/usr/bin/env bash
# setup-real-mode.sh
# 
# Interactive setup script for configuring real Kafka cluster connection.
# Creates .env.local with the correct settings.
#
# Usage:
#   ./scripts/setup-real-mode.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env.local"

echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  Agent Mesh SRE — Real Mode Setup                                    │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
echo ""

# Check if .env.local already exists
if [ -f "$ENV_FILE" ]; then
  echo "⚠ Warning: $ENV_FILE already exists."
  read -p "  Overwrite? (y/N): " OVERWRITE
  if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
    echo "  Aborted."
    exit 0
  fi
fi

echo ""
echo "Select your Kafka provider:"
echo "  1) Confluent Cloud"
echo "  2) Aiven"
echo "  3) RedPanda Cloud"
echo "  4) Strimzi on Kubernetes"
echo "  5) Custom / Other"
echo ""
read -p "Choice (1-5): " PROVIDER

case "$PROVIDER" in
  1)
    PROVIDER_NAME="Confluent Cloud"
    DEFAULT_MECHANISM="plain"
    SSL_ENABLED="true"
    NEEDS_CA="false"
    ;;
  2)
    PROVIDER_NAME="Aiven"
    DEFAULT_MECHANISM="scram-sha-256"
    SSL_ENABLED="true"
    NEEDS_CA="true"
    ;;
  3)
    PROVIDER_NAME="RedPanda Cloud"
    DEFAULT_MECHANISM="scram-sha-256"
    SSL_ENABLED="true"
    NEEDS_CA="false"
    ;;
  4)
    PROVIDER_NAME="Strimzi"
    DEFAULT_MECHANISM="scram-sha-512"
    SSL_ENABLED="true"
    NEEDS_CA="true"
    ;;
  *)
    PROVIDER_NAME="Custom"
    DEFAULT_MECHANISM="scram-sha-256"
    SSL_ENABLED="true"
    NEEDS_CA="false"
    ;;
esac

echo ""
echo "Configuring for: $PROVIDER_NAME"
echo ""

# Collect bootstrap server
read -p "Bootstrap server (e.g., broker.example.com:9092): " BOOTSTRAP
if [ -z "$BOOTSTRAP" ]; then
  echo "✗ Bootstrap server is required"
  exit 1
fi

# Collect username
read -p "SASL username (API key for Confluent): " USERNAME

# Collect password
read -s -p "SASL password (API secret for Confluent): " PASSWORD
echo ""

# Collect SASL mechanism
read -p "SASL mechanism [$DEFAULT_MECHANISM]: " MECHANISM
MECHANISM="${MECHANISM:-$DEFAULT_MECHANISM}"

# Collect SSL setting
read -p "SSL enabled? (true/false) [$SSL_ENABLED]: " SSL_INPUT
SSL_ENABLED="${SSL_INPUT:-$SSL_ENABLED}"

# Collect CA cert if needed
CA_CERT_B64=""
if [ "$NEEDS_CA" = "true" ]; then
  echo ""
  echo "CA certificate (base64 encoded, or path to PEM file):"
  read -p "  Enter value or file path: " CA_INPUT
  if [ -f "$CA_INPUT" ]; then
    CA_CERT_B64=$(base64 -w0 "$CA_INPUT")
    echo "  ✓ Read CA cert from file"
  else
    CA_CERT_B64="$CA_INPUT"
  fi
fi

# Write .env.local
cat > "$ENV_FILE" << EOF
# ── Agent Mesh SRE — Real Mode Configuration ─────────────────────────────────
# Generated by setup-real-mode.sh on $(date -Iseconds)
# Provider: $PROVIDER_NAME

# ── Kafka Mode ────────────────────────────────────────────────────────────────
KAFKA_MODE=real

# ── Cluster Identity ──────────────────────────────────────────────────────────
KAFKA_NAMESPACE=agent-mesh-sre
KAFKA_CLUSTER=agent-mesh-kafka

# ── Connection Settings ───────────────────────────────────────────────────────
KAFKA_BOOTSTRAP=$BOOTSTRAP
KAFKA_USERNAME=$USERNAME
KAFKA_PASSWORD=$PASSWORD
KAFKA_SASL_MECHANISM=$MECHANISM
KAFKA_SSL_ENABLED=$SSL_ENABLED
EOF

if [ -n "$CA_CERT_B64" ]; then
  echo "KAFKA_CA_CERT_BASE64=$CA_CERT_B64" >> "$ENV_FILE"
fi

# Add SMTP placeholder
cat >> "$ENV_FILE" << 'EOF'

# ── SMTP (optional — for email notifications) ─────────────────────────────────
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-gmail@gmail.com
# SMTP_PASS=your-app-password
# NOTIFICATION_EMAIL=recipient@example.com
EOF

echo ""
echo "✓ Configuration written to $ENV_FILE"
echo ""

# Test connection
echo "→ Testing connection..."
cd "$PROJECT_DIR"

# Start the dev server briefly to test
echo "  (Starting server to test connection...)"
timeout 30 npm run dev &>/dev/null &
DEV_PID=$!
sleep 8

HEALTH=$(curl -s "http://localhost:3000/api/cluster/health" 2>/dev/null || echo '{"ok":false,"error":"Server not ready"}')
kill $DEV_PID 2>/dev/null || true

OK=$(echo "$HEALTH" | jq -r '.ok' 2>/dev/null || echo "false")
if [ "$OK" = "true" ]; then
  BROKERS=$(echo "$HEALTH" | jq -r '.brokerCount')
  echo "  ✓ Connection successful! $BROKERS broker(s) found."
else
  ERROR=$(echo "$HEALTH" | jq -r '.error // "Unknown error"' 2>/dev/null)
  echo "  ⚠ Connection test inconclusive: $ERROR"
  echo "  Run 'npm run dev' and check http://localhost:3000/api/cluster/health"
fi

echo ""
echo "╭──────────────────────────────────────────────────────────────────────╮"
echo "│  Setup complete! Run 'npm run dev' to start the application.         │"
echo "╰──────────────────────────────────────────────────────────────────────╯"
